/'
 * Commonly used styles and colors across diagrams.
 * 
 * @author NeuroSync Team
 '/

!define UI_COLOR #1B5E20
!define UI_COLOR_T1 #E8F5E9
!define UI_COLOR_T2 #C8E6C9
!define UI_COLOR_T3 #A5D6A7
!define UI_COLOR_T4 #81C784

!define LOGIC_COLOR #1976D2
!define LOGIC_COLOR_T1 #E3F2FD
!define LOGIC_COLOR_T2 #BBDEFB
!define LOGIC_COLOR_T3 #90CAF9
!define LOGIC_COLOR_T4 #64B5F6

!define MODEL_COLOR #0097A7
!define MODEL_COLOR_T1 #E0F7FA
!define MODEL_COLOR_T2 #B2EBF2
!define MODEL_COLOR_T3 #80DEEA
!define MODEL_COLOR_T4 #4DD0E1

!define STORAGE_COLOR #E65100
!define STORAGE_COLOR_T1 #FFF3E0
!define STORAGE_COLOR_T2 #FFE0B2
!define STORAGE_COLOR_T3 #FFCC80
!define STORAGE_COLOR_T4 #FFB74D

!define USER_COLOR #000000

skinparam Interface {
    BorderColor grey
    BackgroundColor white
    ArrowColor grey
}

skinparam packageStyle rectangle

skinparam ArrowColor grey
skinparam ArrowThickness 1
skinparam ClassBorderColor grey
skinparam ClassFontSize 13
skinparam ClassFontName Arial
skinparam DefaultFontName Arial
skinparam DefaultFontSize 13

hide footbox
hide members
hide circle
