@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as logic LOGIC_COLOR
participant ":AddressBookParser" as abp LOGIC_COLOR
participant ":ViewNoteCommandParser" as vncp LOGIC_COLOR
participant "v:ViewNoteCommand" as vnc LOGIC_COLOR
participant "r:CommandResult" as cr LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as model MODEL_COLOR
end box

[-> logic : execute("viewnote 1")
activate logic

logic -> abp : parseCommand("viewnote 1")
activate abp

create vncp
abp -> vncp
activate vncp

abp -> vncp : parse("1")

create vnc
vncp -> vnc
activate vnc

vncp --> abp : v:ViewNoteCommand
deactivate vncp
'Hidden arrow to position the destroy marker below the end of the activation bar.
vncp -[hidden]-> abp
destroy vncp

abp --> logic : v:ViewNoteCommand
deactivate abp

logic -> vnc : execute()

vnc -> model : getPatientNotes(index)
activate model
model --> vnc : notes
deactivate model

create cr
vnc -> cr
activate cr
cr --> vnc : r
deactivate cr

vnc --> logic : r
deactivate vnc

[<--logic
deactivate logic

@enduml
